# -*- coding: utf-8 -*-

"""
normalise_space.py: normalise the spaces symbols to a basic space characters

operations:
- remove duplicate, triplicate spaces
- replace unicode characters such as \xa0 and \u202f

base: normalise_whitespace.py

BACKLOG
- can the replacement algorithm not be pre-compiled?
"""

# system
import argparse
import copy
from datetime import date, datetime, time, timedelta
import importlib 
import logging
import os
import string
import random
import time
from typing import List, Set, Dict, Tuple, Optional, Union, Iterable

class NormaliseSpace:

    # training configuration
    def __init__(self):

        """
        :param debug: debugging
        """

        self.normalalisation_character = " "

        
        # BACKLOG: add more of non-trivial whitespaces
        self.whitespace_to_be_replaced = [
                "  "
                , "   "
                , "\xa0" # \xa0 is a non-breaking space in Latin1 (ISO 8859-1), generated by Babel
                , "\u202f" # Babel generates \u202f which is a narrow or thin space (# https://www.fileformat.info/info/unicode/char/202f/index.htm)
                            
                ]

    
    def normalise(self, date_str : str) -> str:
        
        """
        normalise the spaces in date_str

        :param date_str: any string

        :return: string with normalised spaces

        """

        # argument checks
        assert isinstance(date_str, str)

        # NOTE: keep iterating until no more offending whitespace found; this is because changing the string may create patterns that need to be replaced
        while True:
            found = False
            for chars in self.whitespace_to_be_replaced:
                if chars in date_str:
                    date_str = date_str.replace(chars, self.normalalisation_character)
                    found = True    
            
            if not found:
                break

        return date_str

   
